version: '3'

services:
  traefik:
    image: traefik # The official Traefik docker image
    command: --api --docker --docker.exposedbydefault=false # Enables the web UI and tells Traefik to listen to docker
    restart: always
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTPS port todo
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #So that Traefik can listen to the Docker events

networks:
  default:
    external:
      name: websites